import { FormField } from '@/types'

export const dentalTemplates = [
  {
    id: 'dental-exam',
    title: 'Dental Examination Form',
    description: 'Comprehensive dental checkup and examination',
    category: 'examination',
    fields: [
      {
        field_type: 'text' as const,
        label: 'Patient Name',
        placeholder: 'Full name',
        required: true,
        order_index: 0,
      },
      {
        field_type: 'date' as const,
        label: 'Examination Date',
        required: true,
        order_index: 1,
      },
      {
        field_type: 'textarea' as const,
        label: 'Chief Complaint',
        placeholder: 'What brings you in today?',
        required: true,
        order_index: 2,
      },
      {
        field_type: 'checkbox' as const,
        label: 'Dental History',
        options: [
          'Previous dental surgeries',
          'Sensitive teeth',
          'Bleeding gums',
          'Jaw pain/TMJ',
          'Orthodontic treatment',
        ],
        required: false,
        order_index: 3,
      },
      {
        field_type: 'radio' as const,
        label: 'Frequency of Dental Visits',
        options: ['Every 6 months', 'Once a year', 'Only when needed', 'First time'],
        required: true,
        order_index: 4,
      },
      {
        field_type: 'radio' as const,
        label: 'Brushing Frequency',
        options: ['Once daily', 'Twice daily', 'After every meal', 'Rarely'],
        required: true,
        order_index: 5,
      },
      {
        field_type: 'radio' as const,
        label: 'Do you floss?',
        options: ['Daily', 'Sometimes', 'Rarely', 'Never'],
        required: true,
        order_index: 6,
      },
      {
        field_type: 'textarea' as const,
        label: 'Oral Examination Findings',
        placeholder: 'Clinical observations...',
        help_text: 'For doctor use',
        required: false,
        order_index: 7,
      },
      {
        field_type: 'textarea' as const,
        label: 'Treatment Plan',
        placeholder: 'Recommended treatments...',
        help_text: 'For doctor use',
        required: false,
        order_index: 8,
      },
    ],
  },
  {
    id: 'dental-treatment-plan',
    title: 'Dental Treatment Plan',
    description: 'Detailed treatment planning and cost estimation',
    category: 'treatment',
    fields: [
      {
        field_type: 'text' as const,
        label: 'Patient Name',
        required: true,
        order_index: 0,
      },
      {
        field_type: 'date' as const,
        label: 'Treatment Date',
        required: true,
        order_index: 1,
      },
      {
        field_type: 'select' as const,
        label: 'Treatment Type',
        options: [
          'Filling',
          'Root Canal',
          'Crown',
          'Bridge',
          'Extraction',
          'Implant',
          'Teeth Whitening',
          'Orthodontics',
          'Other',
        ],
        required: true,
        order_index: 2,
      },
      {
        field_type: 'text' as const,
        label: 'Tooth Number(s)',
        placeholder: 'e.g., 14, 15, 16',
        required: true,
        order_index: 3,
      },
      {
        field_type: 'textarea' as const,
        label: 'Diagnosis',
        placeholder: 'Clinical diagnosis...',
        required: true,
        order_index: 4,
      },
      {
        field_type: 'textarea' as const,
        label: 'Treatment Procedure',
        placeholder: 'Detailed procedure steps...',
        required: true,
        order_index: 5,
      },
      {
        field_type: 'number' as const,
        label: 'Estimated Cost',
        placeholder: '0',
        required: true,
        order_index: 6,
      },
      {
        field_type: 'date' as const,
        label: 'Follow-up Date',
        required: false,
        order_index: 7,
      },
      {
        field_type: 'textarea' as const,
        label: 'Post-treatment Instructions',
        placeholder: 'Patient care instructions...',
        required: false,
        order_index: 8,
      },
    ],
  },
  {
    id: 'dental-emergency',
    title: 'Dental Emergency Form',
    description: 'Quick assessment for dental emergencies',
    category: 'emergency',
    fields: [
      {
        field_type: 'text' as const,
        label: 'Patient Name',
        required: true,
        order_index: 0,
      },
      {
        field_type: 'phone' as const,
        label: 'Emergency Contact Number',
        required: true,
        order_index: 1,
      },
      {
        field_type: 'select' as const,
        label: 'Emergency Type',
        options: [
          'Severe toothache',
          'Broken/chipped tooth',
          'Knocked out tooth',
          'Lost filling/crown',
          'Abscess',
          'Bleeding',
          'Jaw injury',
          'Other',
        ],
        required: true,
        order_index: 2,
      },
      {
        field_type: 'radio' as const,
        label: 'Pain Level (1-10)',
        options: ['1-3 (Mild)', '4-6 (Moderate)', '7-8 (Severe)', '9-10 (Extreme)'],
        required: true,
        order_index: 3,
      },
      {
        field_type: 'textarea' as const,
        label: 'Description of Emergency',
        placeholder: 'What happened and when?',
        required: true,
        order_index: 4,
      },
      {
        field_type: 'checkbox' as const,
        label: 'Symptoms',
        options: [
          'Swelling',
          'Bleeding',
          'Fever',
          'Difficulty swallowing',
          'Numbness',
        ],
        required: false,
        order_index: 5,
      },
      {
        field_type: 'textarea' as const,
        label: 'Immediate Treatment Given',
        placeholder: 'For doctor use',
        required: false,
        order_index: 6,
      },
    ],
  },
  {
    id: 'orthodontic-consultation',
    title: 'Orthodontic Consultation',
    description: 'Initial assessment for braces and orthodontic treatment',
    category: 'orthodontics',
    fields: [
      {
        field_type: 'text' as const,
        label: 'Patient Name',
        required: true,
        order_index: 0,
      },
      {
        field_type: 'number' as const,
        label: 'Age',
        required: true,
        order_index: 1,
      },
      {
        field_type: 'textarea' as const,
        label: 'Reason for Consultation',
        placeholder: 'Why are you interested in orthodontic treatment?',
        required: true,
        order_index: 2,
      },
      {
        field_type: 'checkbox' as const,
        label: 'Concerns',
        options: [
          'Crooked teeth',
          'Gaps between teeth',
          'Overbite',
          'Underbite',
          'Crowded teeth',
          'Jaw alignment',
        ],
        required: true,
        order_index: 3,
      },
      {
        field_type: 'radio' as const,
        label: 'Previous Orthodontic Treatment?',
        options: ['Yes', 'No'],
        required: true,
        order_index: 4,
      },
      {
        field_type: 'select' as const,
        label: 'Preferred Treatment Type',
        options: [
          'Traditional metal braces',
          'Ceramic braces',
          'Clear aligners (Invisalign)',
          'No preference',
        ],
        required: false,
        order_index: 5,
      },
      {
        field_type: 'textarea' as const,
        label: 'Clinical Assessment',
        placeholder: 'Orthodontist notes...',
        help_text: 'For doctor use',
        required: false,
        order_index: 6,
      },
    ],
  },
  {
    id: 'teeth-cleaning',
    title: 'Teeth Cleaning & Hygiene',
    description: 'Regular dental cleaning and hygiene assessment',
    category: 'hygiene',
    fields: [
      {
        field_type: 'text' as const,
        label: 'Patient Name',
        required: true,
        order_index: 0,
      },
      {
        field_type: 'date' as const,
        label: 'Cleaning Date',
        required: true,
        order_index: 1,
      },
      {
        field_type: 'radio' as const,
        label: 'Last Dental Cleaning',
        options: [
          'Less than 6 months ago',
          '6-12 months ago',
          'More than 1 year ago',
          "Don't remember",
        ],
        required: true,
        order_index: 2,
      },
      {
        field_type: 'checkbox' as const,
        label: 'Current Issues',
        options: [
          'Bad breath',
          'Bleeding gums',
          'Plaque buildup',
          'Tooth sensitivity',
          'Staining',
        ],
        required: false,
        order_index: 3,
      },
      {
        field_type: 'radio' as const,
        label: 'Gum Health',
        options: ['Healthy', 'Mild inflammation', 'Moderate inflammation', 'Severe'],
        required: false,
        order_index: 4,
      },
      {
        field_type: 'checkbox' as const,
        label: 'Procedures Performed',
        options: [
          'Scaling',
          'Polishing',
          'Fluoride treatment',
          'Deep cleaning',
          'X-rays',
        ],
        required: false,
        order_index: 5,
      },
      {
        field_type: 'textarea' as const,
        label: 'Hygienist Notes',
        placeholder: 'Clinical notes...',
        required: false,
        order_index: 6,
      },
      {
        field_type: 'textarea' as const,
        label: 'Recommendations',
        placeholder: 'Oral hygiene recommendations...',
        required: false,
        order_index: 7,
      },
    ],
  },
]

export const getTemplateById = (id: string) => {
  return dentalTemplates.find((template) => template.id === id)
}

export const getTemplatesByCategory = (category: string) => {
  return dentalTemplates.filter((template) => template.category === category)
}
